db.bici.insertMany ([
{
    Modelo: "Electra Loft 7d",
    Marca: "Electra",
    Tipo: "Electrica",
    PreciodeCompra: 150,
    PreciodeVenta: 270,
    UnidadesDisponibles: 29,
    Color: "Blanco",
    FechadeVenta: new Date("2020-05-11"),
},
{
    Modelo: "Megamo R10 105 2021",
    Marca: "Megamo",
    Tipo: "Carretera",
    PreciodeCompra: 940,
    PreciodeVenta: 1149,
    UnidadesDisponibles: 21,
    Color: "Azul",
    FechadeVenta: new Date("2015-04-17"),
},
{
    Modelo: "WRC KALIMA GRX400 ALLOY 2021",
    Marca: "WRC",
    Tipo: "Carretera",
    PreciodeCompra: 940,
    PreciodeVenta: 1285,
    UnidadesDisponibles: 14,
    Color: "Amarillo",
    FechadeVenta: new Date("2010-03-11"),
},
{
    Modelo: "Trek Madone SLR eTAP 9 2021",
    Marca: "Treck",
    Tipo: "Carretera",
    PreciodeCompra: 10000,
    PreciodeVenta: 13000,
    UnidadesDisponibles: 4,
    Color: "Azul",
    FechadeVenta: new Date("2020-08-13"),
},
{
    Modelo: "MEGAMO KU2 DISC 26",
    Marca: "Megamo",
    Tipo: "Montaña",
    PreciodeCompra: 150,
    PreciodeVenta: 319,
    UnidadesDisponibles: 32,
    Color: "Verde",
    FechadeVenta: new Date("2020-12-17"),
},
{
    Modelo: "Mondraker Summum R 2020",
    Marca: "Mondraker",
    Tipo: "Montaña",
    PreciodeCompra: 4000,
    PreciodeVenta: 4500,
    UnidadesDisponibles: 10,
    Color: "Azul",
    FechadeVenta: new Date ("2019-07-25"),
},
{
    Modelo: "Trek Roscoe 7 2021",
    Marca: "Trek",
    Tipo: "Montaña",
    PreciodeCompra: 750,
    PreciodeVenta: 1100,
    UnidadesDisponibles: 11,
    Color: "Verde",
    FechadeVenta: new Date("2019-09-19"),
},
{
    Modelo: "Trek Session 8 27.5 GX 2020",
    Marca: "Trek",
    Tipo: "Montaña",
    PreciodeCompra: 2800,
    PreciodeVenta: 3900,
    UnidadesDisponibles: 17,
    Color: "Rojo",
    FechadeVenta:  new Date("2018-07-18"),
},
{
    Modelo: "Conor 7200 29 2021",
    Marca: "Conor",
    Tipo: "Montaña",
    PreciodeCompra: 425,
    PreciodeVenta: 575,
    UnidadesDisponibles: 10,
    Color: "Amarillo",
    FechadeVenta: new Date("2018-06-11"),
},
{
    Modelo: "Conor 5200 2021",
    Marca: "Conor",
    Tipo: "Montaña",
    PreciodeCompra: 150,
    PreciodeVenta: 305,
    UnidadesDisponibles: 18,
    Color: "Rojo",
    FechadeVenta: new Date("2010-01-30"),
},
{
    Modelo: "Megamo Chip 3.0",
    Marca: "Megamo",
    Tipo: "Electrica",
    PreciodeCompra: 740,
    PreciodeVenta: 999,
    UnidadesDisponibles: 27,
    Color: "Blanco",
    FechadeVenta: new Date("2014-08-28"),
},
{
    Modelo: "TREK RAIL 9.8 GX 2020",
    Marca: "Trek",
    Tipo: "Electrica",
    PreciodeCompra: 6100,
    PreciodeVenta: 7200,
    UnidadesDisponibles: 4,
    Color: "Negro",
    FechadeVenta: new Date("2014-09-10"),
},
{
    Modelo: "WETHEPEOPLE NOVA 2020",
    Marca: "Wethepeople",
    Tipo: "BMX",
    PreciodeCompra: 300,
    PreciodeVenta: 450,
    UnidadesDisponibles: 11,
    Color: "Negro",
    FechadeVenta: new Date("2021-01-18"),
},
{
    Modelo: "WETHEPEOPLE CURSE 2020",
    Marca: "Wethepeople",
    Tipo: "BMX",
    PreciodeCompra: 310,
    PreciodeVenta: 499,
    UnidadesDisponibles: 9,
    Color: "Morado",
    FechadeVenta: new Date("2021-01-10"),
},
{
    Modelo: "Megamo Blaze bmx",
    Marca: "Megamo",
    Tipo: "BMX",
    PreciodeCompra: 100,
    PreciodeVenta: 210,
    UnidadesDisponibles: 1,
    Color: "Rojo",
    FechadeVenta: new Date("2017-04-12"),
},
{
    Modelo: "Conor Rave Bmx",
    Marca: "Conor",
    Tipo: "BMX",
    PreciodeCompra: 200,
    PreciodeVenta: 324,
    UnidadesDisponibles: 17,
    Color: "Morado",
    FechadeVenta: new Date("2017-12-31"),
},
{
    Modelo: "MEGAMO FACTORY ELITE 07 2021",
    Marca: "Megamo",
    Tipo: "Carretera",
    PreciodeCompra: 1400,
    PreciodeVenta: 2400,
    UnidadesDisponibles: 16,
    Color: "Negro",
    FechadeVenta: new Date("2017-07-17"),
},
{
    Modelo: "Trek Boone 6 disc 2021",
    Marca: "Trek",
    Tipo: "Carretera",
    PreciodeCompra: 2800,
    PreciodeVenta: 3400,
    UnidadesDisponibles: 6,
    Color: "Blanco",
    FechadeVenta: new Date("2020-09-23"),
},
])